/**
 * 统一错误码常量
 * 
 * 错误码命名规范：
 * - 使用大写字母和下划线
 * - 格式：模块_操作_错误类型
 * - 例如：AUTH_LOGIN_FAILED, USER_NOT_FOUND
 */

export const ErrorCodes = {
  // ========== 通用错误 ==========
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  
  // ========== 认证相关 ==========
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_SESSION_EXPIRED: 'SESSION_EXPIRED',
  AUTH_TOKEN_INVALID: 'TOKEN_INVALID',
  AUTH_FORBIDDEN: 'FORBIDDEN',
  
  // ========== 用户相关 ==========
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_LOCKED: 'USER_LOCKED',
  
  // ========== 激活码相关 ==========
  ACTIVATION_CODE_INVALID: 'ACTIVATION_CODE_INVALID',
  ACTIVATION_CODE_EXPIRED: 'ACTIVATION_CODE_EXPIRED',
  ACTIVATION_CODE_ALREADY_USED: 'ACTIVATION_CODE_ALREADY_USED',
  ACTIVATION_CODE_NOT_FOUND: 'ACTIVATION_CODE_NOT_FOUND',
  
  // ========== API密钥相关 ==========
  API_KEY_INVALID: 'API_KEY_INVALID',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  API_KEY_NOT_SET: 'API_KEY_NOT_SET',
  API_KEY_TEST_FAILED: 'API_KEY_TEST_FAILED',
  
  // ========== 工作流相关 ==========
  WORKFLOW_EXECUTION_ERROR: 'WORKFLOW_EXECUTION_ERROR',
  WORKFLOW_DOMAIN_NOT_FOUND: 'WORKFLOW_DOMAIN_NOT_FOUND',
  WORKFLOW_DOMAIN_UNAVAILABLE: 'WORKFLOW_DOMAIN_UNAVAILABLE',
  WORKFLOW_RELAY_NOT_FOUND: 'WORKFLOW_RELAY_NOT_FOUND',
  WORKFLOW_SENSITIVE_WORD_BLOCKED: 'SENSITIVE_WORD_BLOCKED',
  
  // ========== 聊天相关 ==========
  CHAT_MESSAGE_INVALID: 'CHAT_MESSAGE_INVALID',
  CHAT_HISTORY_NOT_FOUND: 'CHAT_HISTORY_NOT_FOUND',
  
  // ========== 法律相关 ==========
  LEGAL_NOT_SIGNED: 'LEGAL_NOT_SIGNED',
  LEGAL_SIGNATURE_INVALID: 'LEGAL_SIGNATURE_INVALID',
  
  // ========== 会员相关 ==========
  MEMBERSHIP_REQUIRED: 'MEMBERSHIP_REQUIRED',
  MEMBERSHIP_EXPIRED: 'MEMBERSHIP_EXPIRED',
  
  // ========== 管理员相关 ==========
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  ADMIN_OPERATION_FAILED: 'ADMIN_OPERATION_FAILED',
  GET_AI_DOMAINS_FAILED: 'GET_AI_DOMAINS_FAILED',
  GET_ACTIVATION_CODES_FAILED: 'GET_ACTIVATION_CODES_FAILED',
  GET_SYSTEM_CONFIG_FAILED: 'GET_SYSTEM_CONFIG_FAILED',
  EMPTY_CONFIG: 'EMPTY_CONFIG',
  NO_VALID_CONFIG: 'NO_VALID_CONFIG',
  GET_STATS_FAILED: 'GET_STATS_FAILED',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
  REASON_REQUIRED: 'REASON_REQUIRED',
  MEMBERSHIP_UPDATE_DISABLED: 'MEMBERSHIP_UPDATE_DISABLED',
  GET_RELAY_CONFIGS_FAILED: 'GET_RELAY_CONFIGS_FAILED',
  GET_ACTIVE_RELAY_MODELS_FAILED: 'GET_ACTIVE_RELAY_MODELS_FAILED',
  
  // ========== 上游API相关 ==========
  ASSET_PROTECTION_TRIGGERED: 'ASSET_PROTECTION_TRIGGERED',
  LEGAL_GATE_BLOCKED: 'LEGAL_GATE_BLOCKED',
  UPSTREAM_UNAUTHORIZED: 'UPSTREAM_UNAUTHORIZED',
  UPSTREAM_RATE_LIMIT: 'UPSTREAM_RATE_LIMIT',
  UPSTREAM_INSUFFICIENT_BALANCE: 'UPSTREAM_INSUFFICIENT_BALANCE',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
